# Generated by Django 4.2 on 2024-07-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_proj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='course',
            field=models.CharField(default='Default Course', max_length=100),
            preserve_default=False,
        ),
    ]
