# Generated by Django 4.2 on 2024-07-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_proj', '0002_events_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='course',
        ),
    ]
