# Generated by Django 4.2 on 2024-08-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_proj', '0003_remove_events_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='dept',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='events',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
